matrix:
  include:
    - sudo: required
      language: python
      services:
        - docker
    - os: osx
      language: python

script:
  - pip install cibuildwheel==0.6.0 Cython
  - git clone https://github.com/dask/dask-ml
  - cibuildwheel --output-dir wheelhouse dask-ml
